### ISSUE TITLE
Is there a fork that is now 'official' and being maintained

### ISSUE THREAD

**Issue by ttamg** [waytrade/ib-gateway-docker#15]
That's a real shame to hear about your issues with IB.  Sorry to hear that.

Great package here.  Are one of the forks now being maintained as the new 'official' version of this that we can be pointed to, potentially also in the Readme?

Thanks a lot if so.
Matt

**Comment by ttamg** [comment]
If so can we add a note to the README.md so people can be redirected there?  Thanks

**Comment by mfrener** [comment]
Unfortunalty I don't know if someone will continue to provides updates via his repo. 
Usually nobody cares until it stops working, so I keep this open, in case someone comes back with a "here is my repo with updated version".

**Comment by efernandesng** [comment]
First of all, @mfrener thank you for your work on this project!

We used this project, so we decided to create a fork (https://github.com/UnusualAlpha/ib-gateway-docker) and keep maintaining it.

**Comment by mfrener** [comment]
@efernandesng 👍 do you mind if link your repo on the README?

**Comment by efernandesng** [comment]
@mfrener, feel free to do that. TY

**Comment by mfrener** [comment]
done :)
