### ISSUE TITLE
ExitAfterSecondFactorAuthenticationTimeout is set to 'no'

### ISSUE THREAD

**Issue by matandi1** [waytrade/ib-gateway-docker#5]
Hi,

I have trouble setting ExitAfterSecondFactorAuthenticationTimeout to yes via config.ini.

I have updated the default config.ini before running 
`docker build .`
It seems like my config file is copied correctly
```
Step 20/36 : COPY ./config/ibc/config.ini /root/ibc/config.ini
 ---> 0d26351e3a90
```

and
`docker-compose up`

However the output still says
`ib-gateway_1  |     ExitAfterSecondFactorAuthenticationTimeout=no`

Am I missing something I need to do in order to activate my changed config? Or is this a bug?

Thanks
Matandi

**Comment by matandi1** [comment]
Inspecting the container I indeed find that the /root/ibc/config.ini is left in the default version and not replaced with my file. I will continue to investigate

**Comment by mfrener** [comment]
Let me know if you found the problem - when you build locally it should use the config.ini as edited locally (or from you fork repo)
Also, if you have updated to latested IBC already, make sure to also update the config settings
https://github.com/IbcAlpha/IBC/releases/tag/3.12.0-beta.2
`edit your config.ini, replacing the existing Second Factor Authentication Timeout Settings section with the new Second Factor Authentication Settings section from config.ini in the zip file..`
(will update this repo as soon as there is a 3.12 non-beta)

**Comment by matandi1** [comment]
Thank you - I am using IBC: Version: 3.10.0.
Manually changing the config.ini in the container works.
Will now check why the changed config is not copied into the container properly.

**Comment by matandi1** [comment]
No luck in finding the reason so far. I tried to copy a new test.ini file into the container by adding it to Dockerfile in the same way as config.ini. The build indicates that the file was copied:

```
Step 21/37 : COPY ./config/ibc/test.ini /root/ibc/test.ini
 ---> f283bdbaff5d
```
But it turned out that the **file is not copied** into the container.
So I tried if in the container context a normal docker cp would work, which is using the same paths like the COPY command in the docker file. And this is working to copy the file into the container - so the paths should be ok.
`docker cp ./config/ibc/config.ini 279eeea8b71c:/root/ibc/config.ini`

It works for me for the moment - not sure what the problem behind is.
Any ideas?

**Comment by mfrener** [comment]
Just tried to change my local config.ini and rebuild the image, works fine for me (altough login doesn't work anymore because of the 'twsinfo" bug / IBC update still missing}.
Try this checklist:
1) Open the docker-compose.yml and verify there is:
```
build:
      context: .
      dockerfile: ./Dockerfile
``` 
as on it as on repo, not "image: waytrade/ib-gateway:1010" as on README
2) Remove the ./config/ibc/config.ini file
3) Run 'docker-compose up --build'
You must see
=> ERROR [setup 16/17] COPY ./config/ibc/config.ini /root/ibc/config.ini
now, otherwise figure out where  ./config/ibc/config.ini is, you have edited/delte the wrong one as docker build still finds it.

**Comment by matandi1** [comment]
Thank you for the checklist. (1) was correct as in the repo; executing (2) and then (3) led to the error.
I now cloned the repo again and ran docker-compose up --build and it is all working now. 
Looks like the "--build" was the missing piece of the puzzle when running the docker-compose up command.

Thank you for your support!
