### ISSUE TITLE
Version 1012.2c no longer supported.

### ISSUE THREAD

**Issue by electic** [waytrade/ib-gateway-docker#9]
Getting a message like this. Where is the website to get the latest version? Is the the same as the stable version?

**Comment by mfrener** [comment]
Will do an update soon.
Here is stable https://www.interactivebrokers.com/en/index.php?f=16457&ns=T
Here is latest https://www.interactivebrokers.com/en/trading/ibgateway-latest.php
Follow https://www.interactivebrokers.eu/it/index.php?f=16900 to use you local donwload files

Also, 1012.2c is "latest", if you want to use stable instead pull waytrade/ib-gateway:981.3g or change https://github.com/waytrade/ib-gateway-docker/blob/edb2fabb2f12e5cea45d208c65efc99d86f6e42f/Dockerfile#L1 to 981.3g for local build
Version supported via https://github.com/waytrade/ib-gateway-docker/releases are listed here https://github.com/waytrade/ib-gateway-docker#supported-tags

**Comment by electic** [comment]
I see. Seems 1012.2i is the latest now. 1012.2c does not start up. Looking at VNC it says, "Version no longer supported" and prevents it from starting.

**Comment by mfrener** [comment]
[1012.2i](https://github.com/waytrade/ib-gateway-docker/releases/tag/v1012.2i) (latest) and [v981.3j](https://github.com/waytrade/ib-gateway-docker/releases/tag/v981.3j) (stable) now also available via this repo and as prebuild image on [dockerhub](https://hub.docker.com/repository/docker/waytrade/ib-gateway).

**Comment by electic** [comment]
Thank you :)
